<div id='id1' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <img src="./css_estilos/JSLogoFondoClaro.png" style="float: right" width="250" height="230">
     <h1> <b> Generalidades: </b> <br> Análisis Exploratorio de Datos</h1>
     <p> Los archivos fuentes utilizados en el proyecto fueron recuperados de la web, almacenados localmente, y transformados para obtener información relevante, tal como: <p>
     <ul>
          <li> <b> <p> 
          Cantidad de registros totales por categoría
          </b>. </p> </li>
          <li> <b> <p> 
          Cantidad de registros por provincia y categoría 
          </b>. </p> </li>
          <li> <b> <p> 
          Cantidad de registros totales por fuente de datos 
          </b>. </p> </li>
          <li> <b> <p> 
          Cantidad de pantallas, butacas, espacios INCAA por provincia, a partir de la fuente de datos: Salas de Cines
          </b>. </p> </li>
     </ul> 
</body>

---

<div id='id0' > </div>


<head>
    <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
    <title>VIAJES ALEGRES</title>
    <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
    <h1> <b> Índice </b> </h1>
</body>

1.  [<p style="font-family: rubik"> Generalidades </p>](#id1)
2.  [<p style="font-family: rubik"> Características Preliminares de las Fuentes de Datos </p>](#id2)
3.  [<p style="font-family: rubik"> Imoportación de la Librerías Requeridas </p>](#id3)
4.  [<p style="font-family: rubik"> Extración de los Datos </p>](#id4)
5.  [<p style="font-family: rubik"> Carga de los Datos en Dataframes </p>](#id5)
6.  [<p style="font-family: rubik"> Fuente de Datos: Bibliotecas Populares </p>](#id6)
7.  [<p style="font-family: rubik"> Fuente de Datos: Museos </p>](#id7)
8.  [<p style="font-family: rubik"> Fuente de Datos: Salas de Cines </p>](#id8)
9.  [<p style="font-family: rubik"> Unión de los Dataframes </p>](#id9)
10. [<p style="font-family: rubik"> Obtención de los Insights </p>](#id10)

---

<div id='id2' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h1> <b> Características Preliminares de las Fuentes de Datos </b> <br> </h1>
     <p>
     Los datasets disponibles corresponden ha datos públicos generados, guardados y publicados por organismos de gobierno de la República Argentina, pertenecen a la categoría de bases georreferenciadas de Espacios Culturales. Se incluyen a aquellos espacios físicos, con diverso grado de formalidad e institucionalización, en donde se realizan con asiduidad y continuidad actividades culturales de diversa índole. <br>
     <br>
     Los recursos recuperados de las fuentes fueron:
          <ul>
               <li> <b> <p> 
               Bibliotecas Especializadas
               </b>. </p> </li>
               <li> <b> <p> 
               Museo 
               </b>. </p> </li>
               <li> <b> <p> 
               Salas de Cine 
               </b>. </p> </li>
               </ul> 
     </p>
</body>

[<p style="font-family: rubik"> Índice </p> ](#id0)

---

<div id='id3' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h1> <b> Imoportación de la Librerías Requeridas </b> <br> </h1>
</body>

In [1]:
#   Importamos la librerías
import requests
from datetime import datetime
from pathlib import Path
import pandas as pd

[<p style="font-family: rubik"> Índice </p> ](#id0)

---

<div id='id4' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h1> <b> Extración de los Datos </b> <br> </h1>
</body>

In [2]:
#   Definimos los directorios y las rutas
main_dir = Path('./dataset')
data_path = "{category}/{year}-{month:02d}/{category}-{day:02d}-{month:02d}-{year}.csv"

In [3]:
#   Creamos una lista de diccionarios para almacenar la categoría y la url
category_list = [
    {
        "name": "museo",
        "url": "https://datos.cultura.gob.ar/dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/4207def0-2ff7-41d5-9095-d42ae8207a5d/download/museos_datosabiertos.csv"

    },
    {
        "name": "sala_cine",
        "url": "https://datos.cultura.gob.ar/dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/392ce1a8-ef11-4776-b280-6f1c7fae16ae/download/cine.csv"
    },
    {
        "name": "biblioteca_popular",
        "url": "https://datos.cultura.gob.ar/dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/01c6c048-dbeb-44e0-8efa-6944f73715d7/download/biblioteca_popular.csv"
    }
    ]

In [4]:
def get_scrap(category_list):
    for i in range(len(category_list)):
        now = datetime.now()
        category = category_list[i]["name"]
        year = now.year
        month = now.month
        day = now.day
        
        r = requests.get(category_list[i]["url"])
        r.encoding = 'utf-8'
        fl_path = data_path.format(category = category, year = year, 
                                    month = month, day = day)

        main_path = main_dir/fl_path
        main_path.parent.mkdir(parents=True,exist_ok=True)

        with open(main_path,'w') as file_outp:
            file_outp.write(r.text)
            file_name = "{category}-{day:02d}-{month:02d}-{year}.csv".format(category = category, 
                                                                            year = year, 
                                                                            month = month, 
                                                                            day = day)
            print(f"Se ha guardado el archivo: {file_name} \nEn el directorio: {main_path} \n")

In [5]:
get_scrap(category_list = category_list)

Se ha guardado el archivo: museo-20-07-2022.csv
En el directorio: dataset/museo/2022-07/museo-20-07-2022.csv

Se ha guardado el archivo: sala_cine-20-07-2022.csv
En el directorio: dataset/sala_cine/2022-07/sala_cine-20-07-2022.csv

Se ha guardado el archivo: biblioteca_popular-20-07-2022.csv
En el directorio: dataset/biblioteca_popular/2022-07/biblioteca_popular-20-07-2022.csv

[<p style="font-family: rubik"> Índice </p> ](#id0)

---

<div id='id5' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h1> <b> Carga de los Datos en Dataframes </b> <br> </h1>
</body>

<div id='id6' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h2> <b> Fuente de Datos</b>: Bibliotecas Populares </h2>
</body>

In [7]:
#   Declaramos los parámetros para la carga del dataframe
path = "./dataset/biblioteca_popular/2022-07/biblioteca_popular-20-07-2022.csv"
sep = ","
cod = "utf-8"

library_df = pd.read_csv(filepath_or_buffer = path, delimiter = sep, encoding = cod)

In [8]:
#   Visualizamos preliminarmente el dataframe
library_df.head()

,Cod_Loc,IdProvincia,IdDepartamento,Observacion,Categoría,Subcategoria,Provincia,Departamento,Localidad,Nombre,...,Mail,Web,Información adicional,Latitud,Longitud,TipoLatitudLongitud,Fuente,Tipo_gestion,año_inicio,Año_actualizacion
0,70049060,70,70049,NaN,Bibliotecas Populares,NaN,San Juan,Iglesia,Rodeo,Biblioteca Popular Juan P. Garramuno,...,s/d,NaN,NaN,-30.209250,-69.130117,Localización precisa,CONABIP,Comunitaria,1930.0,2018
1,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Helena Larroque de Roffo,...,asociacionroffo@yahoo.com.ar,NaN,NaN,-34.598461,-58.494690,Localización precisa,CONABIP,Comunitaria,1916.0,2018
2,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular 12 de Octubre,...,popular12deoctubre@hotmail.com,NaN,NaN,-34.613235,-58.448997,Localización precisa,CONABIP,Comunitaria,1910.0,2018
3,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Villa Pueyrredón Norte,...,bibliotecapueyrredon@hotmail.com,NaN,NaN,-34.575890,-58.501591,Localización precisa,CONABIP,Comunitaria,1916.0,2018
4,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Alberdi,...,bibliotecapopularalberdi@yahoo.com.ar,NaN,NaN,-34.596157,-58.437668,Localización precisa,CONABIP,Comunitaria,1910.0,2018

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Identificación de los Tipos de Datos </b> </h3>
</body>

In [9]:
#   Visualizamos las columnas del dataframe y sus tipos de datos
library_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Cod_Loc                2017 non-null   int64
 1   IdProvincia            2017 non-null   int64
 2   IdDepartamento         2017 non-null   int64
 3   Observacion            0 non-null      float64
 4   Categoría              2017 non-null   object
 5   Subcategoria           0 non-null      float64
 6   Provincia              2017 non-null   object
 7   Departamento           2017 non-null   object
 8   Localidad              2017 non-null   object
 9   Nombre                 2017 non-null   object
 10  Domicilio              2017 non-null   object
 11  Piso                   0 non-null      float64
 12  CP                     2017 non-null   object
 13  Cod_tel                2017 non-null   object
 14  Teléfono               2017 non-null   object
 15  Mail                   2017 non-null   object
 16  Web                    0 non-null      float64
 17  Información adicional  0 non-null      float64
 18  Latitud                2017 non-null   float64
 19  Longitud               2017 non-null   float64
 20  TipoLatitudLongitud    2017 non-null   object
 21  Fuente                 2017 non-null   object
 22  Tipo_gestion           2017 non-null   object
 23  año_inicio             2010 non-null   float64
 24  Año_actualizacion      2017 non-null   int64
dtypes: float64(8), int64(4), object(13)
memory usage: 394.1+ KB

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Selección de las Columnas de Interes </b> </h3>
</body>

In [10]:
#   Definimos las columnas que deseamos conservar
columns = [ 
            "Cod_Loc", 
            "IdProvincia", 
            "IdDepartamento", 
            "Categoría", 
            "Provincia", 
            "Localidad", 
            "Nombre", 
            "Domicilio", 
            "CP",
            "Teléfono", 
            "Mail", 
            "Web"
            ]

In [11]:
#   Duplicamos el dataframe original conservando únicamente las columnas de interes
library_edit_df = library_df[columns]

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Renombrado de las Columnas </b> </h3>
</body>

In [12]:
#   Definimos la nueva denominación que tendrán las columnas de interes
renamed_columns = {
                    "Cod_Loc":"cod_localidad",
                    "IdProvincia":"id_provincia",
                    "IdDepartamento":"id_departamento",
                    "Categoría":"categoria",
                    "Provincia":"provincia",
                    "Localidad":"localidad",
                    "Nombre":"nombre",
                    "Domicilio":"domicilio",
                    "CP":"codigo_postal",
                    "Teléfono":"numero_de_telefono",
                    "Mail":"mail",
                    "Web":"web"
                    }

In [13]:
#   Renombramos el dataframe
library_edit_df.rename(columns = renamed_columns, inplace = True)

/tmp/ipykernel_37097/405430763.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  library_edit_df.rename(columns = renamed_columns, inplace = True)

In [14]:
#   Comprobamos que el dataframe haya sido actualizado con los cambios indicados
library_edit_df.head()

,cod_localidad,id_provincia,id_departamento,categoria,provincia,localidad,nombre,domicilio,codigo_postal,numero_de_telefono,mail,web
0,70049060,70,70049,Bibliotecas Populares,San Juan,Rodeo,Biblioteca Popular Juan P. Garramuno,Santo Domingo,5465,s/d,s/d,NaN
1,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Helena Larroque de Roffo,Simbrón 3058,C1417EUD,45010078,asociacionroffo@yahoo.com.ar,NaN
2,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular 12 de Octubre,Calle Arengreen 1187,C1405CYM,49880766,popular12deoctubre@hotmail.com,NaN
3,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Villa Pueyrredón Norte,Cockrane 2334,C1419FMD,45729107,bibliotecapueyrredon@hotmail.com,NaN
4,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Alberdi,Acevedo 666,C1414DJN,47753325,bibliotecapopularalberdi@yahoo.com.ar,NaN

[<p style="font-family: rubik"> Índice </p> ](#id0)

---

<div id='id7' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h2> <b> Fuente de Datos</b>: Museos </h2>
</body>

In [15]:
#   Declaramos los parámetros para la carga del dataframe
path = "./dataset/museo/2022-07/museo-20-07-2022.csv"
sep = ","
cod = "utf-8"

museum_df = pd.read_csv(filepath_or_buffer = path, delimiter = sep, encoding = cod)

In [16]:
#   Visualizamos preliminarmente el dataframe
museum_df.head()

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,categoria,subcategoria,provincia,localidad,nombre,direccion,...,Mail,Web,Latitud,Longitud,TipoLatitudLongitud,Info_adicional,fuente,jurisdiccion,año_inauguracion,actualizacion
0,6588100,6,6588,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,9 de Julio,Archivo Y Museo Histórico Gral. Julio De Vedia,Libertad 1191,...,archivoymuseo@yahoo.com.ar,www.portaldel9.com.ar,-35.441762,-60.887598,Localización precisa,NaN,DNPyM,Municipal,1920.0,2017
1,6077010,6,6077,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Arrecifes,Museo Y Archivo Histórico De Arrecifes,Gerardo Risso y España,...,museoarrecifes@hotmail.com,NaN,-34.066970,-60.102555,Localización precisa,NaN,DNPyM,Municipal,1972.0,2017
2,6035010,6,6035,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Avellaneda,Museo Histórico-Sacro Hno. Rogelio Scortegagna,Calle 11 (Av. San Martín) Nº 830,...,NaN,NaN,-29.118024,-59.654543,Localización precisa,NaN,DNPyM,Municipal,NaN,2017
3,6035010,6,6035,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Avellaneda,Museo Municipal De Artes Plásticas De Avellaneda,"Sarmiento 101, 1 º Piso",...,NaN,NaN,-34.662110,-58.363270,Localización precisa,NaN,DNPyM,Municipal,1956.0,2017
4,6049020,6,6049,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Azul,Museo Etnográfico Y Archivo Histórico Enrique ...,Bartolomé J. Ronco 654,...,museoazul@yahoo.com,NaN,-36.781824,-59.858636,Localización precisa,NaN,DNPyM,Privada,1949.0,2017

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Identificación de los Tipos de Datos </b> </h3>
</body>

In [17]:
#   Visualizamos las columnas del dataframe y sus tipos de datos
museum_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Cod_Loc              1182 non-null   int64
 1   IdProvincia          1182 non-null   int64
 2   IdDepartamento       1182 non-null   int64
 3   Observaciones        0 non-null      float64
 4   categoria            1182 non-null   object
 5   subcategoria         1049 non-null   object
 6   provincia            1182 non-null   object
 7   localidad            1182 non-null   object
 8   nombre               1182 non-null   object
 9   direccion            1164 non-null   object
 10  piso                 0 non-null      float64
 11  CP                   1116 non-null   object
 12  cod_area             989 non-null    float64
 13  telefono             988 non-null    object
 14  Mail                 264 non-null    object
 15  Web                  75 non-null     object
 16  Latitud              1182 non-null   float64
 17  Longitud             1182 non-null   float64
 18  TipoLatitudLongitud  1182 non-null   object
 19  Info_adicional       10 non-null     object
 20  fuente               1182 non-null   object
 21  jurisdiccion         1085 non-null   object
 22  año_inauguracion     643 non-null    float64
 23  actualizacion        1182 non-null   int64
dtypes: float64(6), int64(4), object(14)
memory usage: 221.8+ KB

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Selección de las Columnas de Interes </b> </h3>
</body>

In [18]:
#   Definimos las columnas que deseamos conservar
columns = [ 
            "Cod_Loc", 
            "IdProvincia", 
            "IdDepartamento", 
            "categoria", 
            "provincia", 
            "localidad", 
            "nombre", 
            "direccion", 
            "CP",
            "telefono", 
            "Mail", 
            "Web"
            ]

In [19]:
#   Duplicamos el dataframe original conservando únicamente las columnas de interes
museum_edit_df = museum_df[columns]

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Renombrado de las Columnas </b> </h3>
</body>

In [20]:
#   Definimos la nueva denominación que tendrán las columnas de interes
renamed_columns = {
                    "Cod_Loc":"cod_localidad", 
                    "IdProvincia":"id_provincia", 
                    "IdDepartamento":"id_departamento",
                    "categoria":"categoria", 
                    "provincia":"provincia", 
                    "localidad":"localidad", 
                    "nombre":"nombre", 
                    "direccion":"domicilio", 
                    "CP":"codigo_postal", 
                    "telefono":"numero_de_telefono", 
                    "Mail":"mail", 
                    "Web":"web"
                    }

In [21]:
#   Renombramos el dataframe
museum_edit_df.rename(columns = renamed_columns, inplace = True)

/tmp/ipykernel_37097/2237495416.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  museum_edit_df.rename(columns = renamed_columns, inplace = True)

In [22]:
#   Comprobamos que el dataframe haya sido actualizado con los cambios indicados
museum_edit_df.head()

,cod_localidad,id_provincia,id_departamento,categoria,provincia,localidad,nombre,domicilio,codigo_postal,numero_de_telefono,mail,web
0,6588100,6,6588,Espacios de Exhibición Patrimonial,Buenos Aires,9 de Julio,Archivo Y Museo Histórico Gral. Julio De Vedia,Libertad 1191,B6500EVL,425 279,archivoymuseo@yahoo.com.ar,www.portaldel9.com.ar
1,6077010,6,6077,Espacios de Exhibición Patrimonial,Buenos Aires,Arrecifes,Museo Y Archivo Histórico De Arrecifes,Gerardo Risso y España,B2740FMJ,452 931,museoarrecifes@hotmail.com,NaN
2,6035010,6,6035,Espacios de Exhibición Patrimonial,Buenos Aires,Avellaneda,Museo Histórico-Sacro Hno. Rogelio Scortegagna,Calle 11 (Av. San Martín) Nº 830,S3561AKT,481 200,NaN,NaN
3,6035010,6,6035,Espacios de Exhibición Patrimonial,Buenos Aires,Avellaneda,Museo Municipal De Artes Plásticas De Avellaneda,"Sarmiento 101, 1 º Piso",B1870CBC,4205 9567,NaN,NaN
4,6049020,6,6049,Espacios de Exhibición Patrimonial,Buenos Aires,Azul,Museo Etnográfico Y Archivo Histórico Enrique ...,Bartolomé J. Ronco 654,B7300XAA,434 811,museoazul@yahoo.com,NaN

[<p style="font-family: rubik"> Índice </p> ](#id0)

---

<div id='id8' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h2> <b> Fuente de Datos</b>: Salas de Cines </h2>
</body>

In [23]:
#   Declaramos los parámetros para la carga del dataframe
path = "./dataset/sala_cine/2022-07/sala_cine-20-07-2022.csv"
sep = ","
cod = "utf-8"

cine_df = pd.read_csv(filepath_or_buffer = path, delimiter = sep, encoding = cod)

In [24]:
#   Visualizamos preliminarmente el dataframe
cine_df.head()

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,Categoría,Provincia,Departamento,Localidad,Nombre,Dirección,...,Información adicional,Latitud,Longitud,TipoLatitudLongitud,Fuente,tipo_gestion,Pantallas,Butacas,espacio_INCAA,año_actualizacion
0,10049030,10,10049,NaN,Salas de cine,Catamarca,Capital,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,...,NaN,-28.464737,-65.800675,Localización precisa,INCAA / SInCA,Privado comercial,5,743,NaN,2018
1,10091150,10,10091,NaN,Salas de cine,Catamarca,Santa Maria,Santa María,Centro Cultural San Agustín,San Martin 173,...,NaN,-26.693859,-66.049058,Localización precisa,INCAA / SInCA,Privado comercial,1,440,0,2018
2,22140060,22,22140,NaN,Salas de cine,Chaco,San Fernando,Resistencia,Los Cines De La Costa,Av. Sarmiento 2600,...,NaN,-27.430995,-58.962672,Localización precisa,INCAA / SInCA,Privado comercial,5,820,NaN,2018
3,26091020,26,26091,NaN,Salas de cine,Chubut,Sarmiento,Sarmiento,Deborah Jones De Williams,Reg. Inf. Mec. 25 Esquina 20 De Junio,...,NaN,-45.594374,-69.069594,Localización precisa,INCAA / SInCA,Público municipal,1,80,NaN,2018
4,18007010,18,18007,NaN,Salas de cine,Corrientes,Bella Vista,Bella Vista,Fantasio,Salta 1059,...,NaN,-28.508494,-59.045464,Localización precisa,INCAA / SInCA,Privado comercial,1,240,NaN,2018

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Identificación de los Tipos de Datos </b> </h3>
</body>

In [25]:
#   Visualizamos las columnas del dataframe y sus tipos de datos
cine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Cod_Loc                329 non-null    int64
 1   IdProvincia            329 non-null    int64
 2   IdDepartamento         329 non-null    int64
 3   Observaciones          0 non-null      float64
 4   Categoría              329 non-null    object
 5   Provincia              329 non-null    object
 6   Departamento           329 non-null    object
 7   Localidad              329 non-null    object
 8   Nombre                 329 non-null    object
 9   Dirección              329 non-null    object
 10  Piso                   329 non-null    object
 11  CP                     329 non-null    int64
 12  cod_area               329 non-null    object
 13  Teléfono               329 non-null    object
 14  Mail                   329 non-null    object
 15  Web                    329 non-null    object
 16  Información adicional  0 non-null      float64
 17  Latitud                329 non-null    float64
 18  Longitud               329 non-null    float64
 19  TipoLatitudLongitud    329 non-null    object
 20  Fuente                 329 non-null    object
 21  tipo_gestion           329 non-null    object
 22  Pantallas              329 non-null    int64
 23  Butacas                329 non-null    int64
 24  espacio_INCAA          64 non-null     object
 25  año_actualizacion      329 non-null    int64
dtypes: float64(4), int64(7), object(15)
memory usage: 67.0+ KB

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Selección de las Columnas de Interes </b> </h3>
</body>

In [26]:
#   Definimos las columnas que deseamos conservar
columns = [ 
            "Cod_Loc", 
            "IdProvincia", 
            "IdDepartamento", 
            "Categoría", 
            "Provincia", 
            "Localidad", 
            "Nombre", 
            "Dirección", 
            "CP", 
            "Teléfono", 
            "Mail", 
            "Web"
            ]

In [27]:
#   Duplicamos el dataframe original conservando únicamente las columnas de interes
cine_edit_df = cine_df[columns]

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h3> <b> Renombrado de las Columnas </b> </h3>
</body>

In [28]:
#   Definimos la nueva denominación que tendrán las columnas de interes
renamed_columns = {
                    "Cod_Loc":"cod_localidad",
                    "IdProvincia":"id_provincia",
                    "IdDepartamento":"id_departamento",
                    "Categoría":"categoria",
                    "Provincia":"provincia",
                    "Localidad":"localidad",
                    "Nombre":"nombre",
                    "Dirección":"domicilio",
                    "CP":"codigo_postal",
                    "Teléfono":"numero_de_telefono",
                    "Mail":"mail",
                    "Web":"web"
                    }

In [29]:
#   Renombramos el dataframe
cine_edit_df.rename(columns = renamed_columns, inplace = True)

/tmp/ipykernel_37097/1090936705.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cine_edit_df.rename(columns = renamed_columns, inplace = True)

In [30]:
#   Comprobamos que el dataframe haya sido actualizado con los cambios indicados
cine_edit_df.head()

,cod_localidad,id_provincia,id_departamento,categoria,provincia,localidad,nombre,domicilio,codigo_postal,numero_de_telefono,mail,web
0,10049030,10,10049,Salas de cine,Catamarca,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,4700,s/d,s/d,http://www.cinemacenter.com.ar/
1,10091150,10,10091,Salas de cine,Catamarca,Santa María,Centro Cultural San Agustín,San Martin 173,4139,421511,s/d,s/d
2,22140060,22,22140,Salas de cine,Chaco,Resistencia,Los Cines De La Costa,Av. Sarmiento 2600,3500,472200,administracion@loscinesdelacosta.com.ar,http://resistencia.loscinesdelacosta.com.ar/
3,26091020,26,26091,Salas de cine,Chubut,Sarmiento,Deborah Jones De Williams,Reg. Inf. Mec. 25 Esquina 20 De Junio,9020,4897169,culturasarmiento@hotmail.com,http://www.culturachubut.gob.ar/…/convo-evita-...
4,18007010,18,18007,Salas de cine,Corrientes,Bella Vista,Fantasio,Salta 1059,3432,s/d,nuevocineteatrorex@gmail.com,https://www.facebook.com/CineFantasioBellaVista/

[<p style="font-family: rubik"> Índice </p> ](#id0)

---

<div id='id9' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h2> <b> Unión de los Dataframes </b> </h2>
</body>

In [31]:
#   Agrupamos en un diccionario las fuentes de datos y sus respectivos dataframes
df_dict = {
            "bibliotecas_polulares": library_edit_df, 
            "museos": museum_edit_df, 
            "salas_cine": cine_edit_df
            }

In [32]:
#   Concatenamos en un único dataframe los datos recuperados de las fuentes indicadas
culture_df = pd.concat(df_dict, axis = 0, ignore_index=True)

In [33]:
#   Comprobamos que el dataframe haya sido creado correctamente
culture_df.head()

,cod_localidad,id_provincia,id_departamento,categoria,provincia,localidad,nombre,domicilio,codigo_postal,numero_de_telefono,mail,web
0,70049060,70,70049,Bibliotecas Populares,San Juan,Rodeo,Biblioteca Popular Juan P. Garramuno,Santo Domingo,5465,s/d,s/d,NaN
1,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Helena Larroque de Roffo,Simbrón 3058,C1417EUD,45010078,asociacionroffo@yahoo.com.ar,NaN
2,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular 12 de Octubre,Calle Arengreen 1187,C1405CYM,49880766,popular12deoctubre@hotmail.com,NaN
3,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Villa Pueyrredón Norte,Cockrane 2334,C1419FMD,45729107,bibliotecapueyrredon@hotmail.com,NaN
4,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Alberdi,Acevedo 666,C1414DJN,47753325,bibliotecapopularalberdi@yahoo.com.ar,NaN

[<p style="font-family: rubik"> Índice </p> ](#id0)

---

<div id='id10' > </div>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h1> <b> Obtención de los Insights </b> <br> </h1>
</body>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h2> <b> A partir de: </b> "culture_df" </h2>
</body>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
    <ul>
        <li> <b> <p> 
        Cantidad de registros totales por categoría
        </b>: </p> </li>
    </ul> 
</body>

In [34]:
#   Agrupamos por categoría y contabilizamos los regístros
culture_df.groupby(["categoria"], as_index=False).size()

                            categoria  size
0               Bibliotecas Populares  2017
1  Espacios de Exhibición Patrimonial  1182
2                       Salas de cine   329

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
    <ul>
        <li> <b> <p> 
        Cantidad de registros por provincia y categoría 
        </b>: </p> </li>
    </ul> 
</body>

In [35]:
#   Agrupamos por categoría y provincia, luego contabilizamos los regístros
culture_df.groupby(["categoria", "provincia"], as_index=False).size()

                categoria                        provincia  size
0   Bibliotecas Populares                     Buenos Aires   543
1   Bibliotecas Populares                        Catamarca    38
2   Bibliotecas Populares                            Chaco    70
3   Bibliotecas Populares                           Chubut    48
4   Bibliotecas Populares  Ciudad Autónoma de Buenos Aires    43
..                    ...                              ...   ...
68          Salas de cine                       Santa Cruz     5
69          Salas de cine                         Santa Fe    23
70          Salas de cine              Santiago del Estero     5
71          Salas de cine                 Tierra del Fuego     3
72          Salas de cine                          Tucumán     8

[73 rows x 3 columns]

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
    <ul>
        <li> <b> <p> 
        Cantidad de registros totales por fuente de datos 
        </b>: </p> </li>
    </ul> 
</body>

In [36]:
#   Contabilizamos los elementos del dataframe y los segregamos por fuente de datos, a partir del diccionario de dataframes
lst = list()
for name, df in df_dict.items():
    lst.append({"source": name, "count":df.size})

In [39]:
#   Mostramos en un dataframe la segmentación resultante
pd.DataFrame(lst)

                  source  count
0  bibliotecas_polulares  24204
1                 museos  14184
2             salas_cine   3948

[<p style="font-family: rubik"> Índice </p> ](#id0)

---

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
     <h2> <b> A partir de: </b> "cine_df" </h2>
     <p> Procesar la información para poder crear una tabla que contenga; </p>
</body>

<head>
     <meta http-equiv="Content-Type"content="text/html"charset="utf-8">
     <title>VIAJES ALEGRES</title>
     <link href="./css_estilos/estilo_01.css"rel="stylesheet"type="text/css"> 
</head>
<body>
    <ul>
        <li> <b> <p> 
        Provincia.
        </b> </p> </li>
        <li> <b> <p> 
        Cantidad de pantallas.
        </b> </p> </li>
        <li> <b> <p> 
        Cantidad de butacas.
        </b> </p> </li>
        <li> <b> <p> 
        Cantidad de espacios INCAA.
        </b> </p> </li>
    </ul> 
</body>

In [40]:
#   Agrupamos por categoría y contabilizamos el número de patallas, butacas y espacios INCAA
cine_df.groupby("Provincia", as_index=False).count()[["Provincia", "Pantallas", "Butacas", "espacio_INCAA"]]

                          Provincia  Pantallas  Butacas  espacio_INCAA
0                      Buenos Aires        106      106             20
1                         Catamarca          4        4              2
2                             Chaco          4        4              1
3                            Chubut          9        9              4
4   Ciudad Autónoma de Buenos Aires         35       35              3
5                        Corrientes          8        8              1
6                           Córdoba         35       35              2
7                        Entre Ríos         13       13              2
8                           Formosa          2        2              1
9                             Jujuy          4        4              2
10                         La Pampa          6        6              2
11                         La Rioja          5        5              1
12                          Mendoza         16       16              2
13                         Misiones          6        6              2
14                          Neuquén          5        5              3
15                        Río Negro          7        7              4
16                            Salta         10       10              2
17                         San Juan          6        6              2
18                         San Luis          4        4              0
19                       Santa Cruz          5        5              2
20                         Santa Fe         23       23              3
21              Santiago del Estero          5        5              1
22                 Tierra del Fuego          3        3              0
23                          Tucumán          8        8              2

[<p style="font-family: rubik"> Índice </p> ](#id0)

---